version: "3.9"
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/1_qingqu1024.com_bundle.crt:/etc/nginx/1_qingqu1024.com_bundle.crt
            - ./nginx/2_qingqu1024.com.key:/etc/nginx/2_qingqu1024.com.key
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - node-app

    db:
        image: postgres:13
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - /db/pgData/:/var/lib/postgresql/data

    node-app:
        build: .
        command: yarn start
        depends_on:
            - db
