version: "3.9"
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "80:80"

    node-app:
        build: .
        command: yarn start
